### ISSUE TITLE
Getting error in Bevy 0.16.0

### ISSUE THREAD

**Issue by MyCADDev** [Adamekka/bevy-fps-counter#8]
the trait bound `FpsCounterPlugin: Plugins<_>` is not satisfied
you can use `cargo tree` to explore your dependency tree
required for `FpsCounterPlugin` to implement `Plugins<_>`

**Comment by Adamekka** [comment]
Because this lib is only up to date with Bevy 0.15, I'll update it to 0.16

**Comment by Adamekka** [comment]
change version in `Cargo.toml` to `0.7.0`

```toml
[dependencies]
bevy-fps-counter = "0.7.0"
```
